sudo: false
dist: trusty
language: generic
git:
  submodules: true
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - g++-5
    - gcc-5
    - libtool
    - autoconf
    - automake
    - cmake
    - cmake-data
    - pkg-config
    - unzip
script:
  - YCM_CORES=1 CXX=g++-5 CC=gcc-5 ./build.sh
before_deploy:
- export PACKAGE_NAME=nvim-${TRAVIS_OS_NAME}
- echo "Preparing package ${PACKAGE_NAME}"
- cd install && tar cjf ../${PACKAGE_NAME}.tgz *
deploy:
  provider: releases
  api_key:
    secure: nzLoJpqguyW/29kwZ5/imALsHYhmfF8zZ2uNZ125D9YX5GkrBp8IQ2jIGOj7GpKqq2C+sSnKykRSFQwiuTe0eriZyCll62OG7Ii1EgpxvSrL6mNmU9/qWyZANSrjS6xip+Ozav5Oard5yIxWO8eQ/mnA38gpIkaQd/GmM5o13PU=
  file: ${PACKAGE_NAME}.tgz
  skip_cleanup: true
  on:
    repo: hotgloupi/nvim
    tags: true
    all_branches: true

